FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app
COPY . /app

RUN apt-get update -qq && apt-get install -y netcat-openbsd -qq
COPY migrate.sh /usr/local/bin/migrate.sh
RUN chmod +x /usr/local/bin/migrate.sh
