services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: game_releases
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - game-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d game_releases"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    container_name: migrate
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=game_releases;Username=postgres;Password=1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - game-network

volumes:
  postgres_data:

networks:
  game-network:
    driver: bridge
